[package]
name = "diary-beta-"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
chrono = "0.4.42"
dotenvy = "0.15.7"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
